### ISSUE TITLE
Moving to ros2-gbp release repo

### ISSUE THREAD

**Issue by ijnek** [paulbovbel/zbar_ros#12]
@mikepurvis @paulbovbel 

All release repositories that were in ROS2 Rolling have been forked and moved to [ros2-gbp](https://github.com/ros2-gbp) recently. Moving to ros2-gbp isn't strictly a requirement *yet*, but is recommended, as [mentioned here](https://github.com/ros/rosdistro/pull/32228#issuecomment-1044679217).

I see that [ros-drivers/transport_drivers_release](https://github.com/ros/rosdistro/blob/ebc5ffc7bc81e9f7af8d261d97383d72cb7c3e6f/rolling/distribution.yaml#L4654) has been moved to ros2-gbp already. Are you fine with me moving the release repo across, and adding us three as maintainers over there (and archiving this repo)?

**Comment by paulbovbel** [comment]
You may just want to make a new release repo over there then - otherwise you'd have to update the ros1 rosdistro

**Comment by ijnek** [comment]
That seems reasonable, I will do so.
