### ISSUE TITLE
Split off Distros

### ISSUE THREAD

**Issue by ijnek** [paulbovbel/zbar_ros#18]
Split off:

- [x] Humble
   - [x] Create branch
   - [x] Update rosdistro (https://github.com/ijnek/rosdistro/tree/ijnek-zbar-ros-branch-rename)
- [x] Iron
- [x] Jazzy
- [x] Rolling
   - [x] Rename ros2 branch to rolling, to match core ROS packages
   - [x] Update rosdistro

**Comment by ijnek** [comment]
Hi @paulbovbel, would you be able to either change the ros2 branch name to ``rolling``, or grant me maintain access to this repo so I can do this? Thanks.

**Comment by ijnek** [comment]
[Humble Dev job failure](https://build.ros2.org/job/Hdev__zbar_ros__ubuntu_jammy_amd64/5/console) should be fixed by https://github.com/ros/rosdistro/pull/35695

**Comment by ijnek** [comment]
Hi @paulbovbel, would you be able to either change the ros2 branch name to rolling, or grant me maintain access to this repo so I can do this? Thanks.

**Comment by ijnek** [comment]
Hey @paulbovbel , friendly ping

**Comment by ijnek** [comment]
Could someone help me with obtaining admin privilege @paulbovbel or @clalancette please? I've been maintainer for over 3 years and I can't make simple changes like renaming the default branch to rolling.

**Comment by clalancette** [comment]
Since I'm not a maintainer on this repository, I'm not comfortable changing your permissions (though you are currently listed as a "Maintainer").

That said, if you push a `rolling` branch that matches the current `ros2` here, I'm willing to make that the default.

**Comment by ijnek** [comment]
@clalancette I would appreciate that, thanks! I've created the ``rolling`` branch off ``ros2``

**Comment by clalancette** [comment]
> @clalancette I would appreciate that, thanks! I've created the `rolling` branch off `ros2`

And I've now switched `rolling` to be the default.

**Comment by ijnek** [comment]
Closing, as all PRs to split off distros have been created.
