### ISSUE TITLE
New Release for Indigo/Kinetic

### ISSUE THREAD

**Issue by fmessmer** [paulbovbel/zbar_ros#3]
Hello,
would it be possible to trigger a new release for this repo to both/at least Indigo and Kinetic as we depend on the fix provided in #2 
Thanks!

**Comment by fmessmer** [comment]
@paulbovbel @furushchev @mikepurvis 
any chance of triggering a new release for indigo and kinetic before christmas?

**Comment by paulbovbel** [comment]
Can do, thanks for the reminder

**Comment by fmessmer** [comment]
Thanks!
