### ISSUE TITLE
Couldn't increase fps

### ISSUE THREAD

**Issue by vannem95** [paulbovbel/zbar_ros#5]
I changed the fps param of the uvc_camera node in the launch to 30 but i'm still only getting 3fps.
here is a [link](https://drive.google.com/open?id=1Pvp5qekTLn6YaSADwodhK251A-kP7Utx) of the issue.

How do i get 30 fps?

Thanks in advance

**Comment by paulbovbel** [comment]
This doesn't on the surface seem like a zbar_ros issue. This library will process incoming messages as fast as it can. You should check what the frequency of the output data is _compared_ to the frequency of the input data, and whether your process is CPU or i/o bound (top, nethogs, iotop are all useful tools for this).
