### ISSUE TITLE
package works fine with integrated notebook acer camera but not with external Logitech, Inc. Webcam C270

### ISSUE THREAD

**Issue by Marcelbgit** [paulbovbel/zbar_ros#7]
Hello Paul,

thanks a lot for sharing your code. After testing your package on my integrated laptop camera, I now want to recognize and read QR codes via the external Logitech camera. Unfortunately this does not work and when reading the topic "rostopic echo /barcode" nothing returned and the topic is stuck (previously for example "data: "8000500242131" ). Can you please help me with this? I have added parameters for the camera in the launch file, as you can see below. The camera can also be controlled and outputs images.
_______________________________________________________________________________________________

    
    <node pkg="nodelet" type="nodelet" name="uvc_camera" args="load uvc_camera/CameraNodelet zbar_manager">
    	<param name="device" type="string" value="/dev/video2"/>
        <remap from="image_raw" to="image"/>
    </node> 
_______________________________________________________________________________________________
Best regards and thanks for your help
Marcel

**Comment by paulbovbel** [comment]
Sorry @Marcelbgit, there's not really much I can do here. This package is a pretty thin wrapper of the zbar library. You should check the image resolution and quality to see if that makes any difference.
