### ISSUE TITLE
Porting to ROS2

### ISSUE THREAD

**Issue by ijnek** [paulbovbel/zbar_ros#9]
Hi @paulbovbel , are there any plans on porting this package for ROS2? Or perhaps, is there some alternative package in ROS2 that you know of, which supersedes this package?

I can't seem to come across any Barcode or QR-code packages for ROS2, so I'm thinking of porting this library to ROS2 (and releasing it). It would be good if I can make sure you or any one else is not already working on this.

If porting to ROS2 is desired, I think it may be better to start the ros2 branches in the existing repo, rather than starting a new repo elsewhere.

**Comment by ijnek** [comment]
Hi @paulbovbel just pinging, I've ported the majority over to ROS2 apart from some functionalities, like not publishing unless there's subscribers, and the `throttle_repeated_barcodes` parameter. What's your ideas on the issue?

**Comment by paulbovbel** [comment]
Hi @ijnek, thanks for reaching out! I've created a `ros2` branch, please do PR your changes against that.

Looks like there's still no connect/disconnect callbacks for lazy pub/sub in ROS2 (https://docs.ros2.org/galactic/api/rclcpp/structrclcpp_1_1SubscriptionEventCallbacks.html seems like where it should exist..), so please feel free to leave a TODO for that.

I'd prefer if you kept `throttle_repeated_barcodes` in as I've found it useful in the past, but it's not strictly necessary as it's really something that could be implemented consumer-side.

**Comment by ijnek** [comment]
Great, I'll see if I can port across `thorttle_repeated_barcodes` as it doesn't seem hard to. If it proves to be harder than I anticipate, I may pull it out into a separate PR, or open an issue.

**Comment by ijnek** [comment]
`throttle_repeated_barcodes` has been ported in #10 , PR is up fo review.

**Comment by ijnek** [comment]
#10 merged.
